### PR TITLE
feat: remove defaultProps

### PR DESCRIPTION
**Pull request by squiaios**
Support for defaultProps will be removed from function components in a future major release.

### CODE REVIEW

**Comment by gabrielnafuzi** [comment]
@robmadole Please, merge this PR, thanks!

**Review by gabrielnafuzi — APPROVED** [review]

**Review by barucAlmaguer — APPROVED** [review]

**Comment by Maxou44** [comment]
Any news about this MR ? It's required for React 19 😅

**Comment by robmadole** [comment]
Thanks for the PR. Merging now and then we'll get a release out.

**Comment by Maxou44** [comment]
Thanks @robmadole for the quick reply and the merge :)

**Pull request merged**
