### PR TITLE
add eslint to project

### PR DESCRIPTION
**Pull request by mudrz**
Added `eslint` configuration and packages to project to allow easier collaboration

(edited files are formatted with https://github.com/prettier/prettier)

### CODE REVIEW

**Comment by robmadole** [comment]
We're gonna stick with yarn for the time being, is the `package-lock.json` file necessary?

**Comment by mudrz** [comment]
not really, I am using yarn too

**Comment by robmadole** [comment]
@mudrz let's start with this PR first. We just merged in a bundle of changes. If you can get this rebased with master we'll merge it.

**Comment by mudrz** [comment]
@robmadole I merged master and resolved the version conflicts

**Comment by robmadole** [comment]
I don't think ESLint was configured correctly here. Closing and going through a new setup again.

**Comment by mudrz** [comment]
It was configured absolutely correctly, the official react boilerplate uses the very same setup.
But it is a 3 month old pull request, so it's possible that it's out of date.

**Pull request closed without merging**
