### PR TITLE
Support for setting ref for 16.x

### PR DESCRIPTION
**Pull request by petertriho**
See #200 
Pass ref via forwardedRef prop:
- <= 16.2: pass in callback ref https://reactjs.org/docs/refs-and-the-dom.html#callback-refs
- \>= 16.3: use React.createRef() or
`const MyFontAwesomeIcon = React.forwardRef((props, ref) => (
    <FontAwesomeIcon fowardedRef={ref} {...props} />
));`

### CODE REVIEW

**Comment by circlingthesun** [comment]
Is there any chance of this getting merged soonish?

**Comment by circlingthesun** [comment]
@robmadole, is there anything that needs to be addressed for this to be merged?

**Comment by robmadole** [comment]
Alright, this looks like a good direction for solving this. However we need to update the Travis CI configuration and make sure we have tests for both versions of React. I want to make sure this is working for both versions.

**Comment by reinrl** [comment]
Any more updates on this?

**Comment by robmadole** [comment]
Contributions are welcome on this! We need to get this running in Travis CI as I stated. When I get the time I will work on this. If the community can speed this up by updating the `.travis.yml` that would be fantastic.

**Comment by Floriferous** [comment]
Can I just ask if you are sure you want to support multiple versions of React? This is adding a big burden on a package that many people would want to be a bit leaner and faster at iterating. The react team is adding lots of features without major version bumps, so starting with 2 versions now will only lead to supporting lots of varying versions in the future.

As we are at React 16.12 now, I wonder if we can consider just moving forward on those basic features that have been widely adopted across the React community.

**Comment by robmadole** [comment]
I've updated the CI configuration for this project to use GitHub Actions. We should be able to test with React versions 16.2 and up with it. If this branch is caught up with `master` we can begin to chat about what the impact of this change would bring.

**Pull request closed without merging**
