### PR TITLE
Adding es module to Rollup config

### PR DESCRIPTION
**Pull request by robmadole**

### CODE REVIEW

**Comment by mlwilkerson** [comment]
And would also need to be added to the files key in package.json, right?

**Comment by robmadole** [comment]
@mlwilkerson I think we are leaving `index.js` and kin in the repo so that installs can occur directly from GitHub. It seems like you ran into that during your exploration of this and we committed the file.

I've added `files` to package.json and removed the `.npmignore`.

**Comment by mlwilkerson** [comment]
I didn't remember that we were checking in `index.js` and `index.es.js`. I'm pretty sure I've been fighting back with `.gitignore` and re-deleting `index.js`. I'll defer to you on that. But it makes me wonder whether we'll need to re-assert this decision on the development branch.

**Comment by robmadole** [comment]
Well, I think we ran into this with the good 'ole "external" use case. We had an example that referenced `node_modules/@fortawesome/react-fontawesome/index.js`. Initially the file was not there because it was a fresh clone. We were concerned about how this would impact users who were trying this for the first time and immediately running into an error.

**Comment by mlwilkerson** [comment]
My mind is so wrapped up in knots at this point around all of those considerations, I'm confused... But after learning the system better, now I kinda want to be convinced again from scratch that we really need `index.js` and `index.es.js` to be checked in.

If at one point in working on the external example, I/someone tried to pull in `node_modules/@fortawesome/react-fontawesome/index.js`, I'm not sure why. But it seems like the way the example apps install the react component should be via package.json from npm. 

Or maybe a case could be made that it should be installed by "build the react component and then import the results, copy over the results and import that". 

On the other hand, the purpose of the example apps—in my understanding—isn't so much integration testing for what was just built, but showing what it might look like if you made your own app with the react component. From that standpoint, it might make for a better demo to show how one installs the react component via package.json and `yarn install` (or equiv).

But now it's seeming to me like it we wouldn't want to increase confusion by checking in `index.js`.

If the goal is to make sure that newcomers don't stumble over the first example app they try, then maybe that could alternatively be solved by just making sure that the builds of those example apps don't break as we version the react component. I think that might have been the case when I first started working on the example apps–they were well behind the then-current development of the react component itself. We could add a test to the main react component repo that verifies those example apps build properly. (Caveat: if we wanted the example apps to always depend on the current react code, then the example apps wouldn't install the react component from npm. There would have to be some step to build the react component first and then use or copy the build results.)

**Comment by robmadole** [comment]
@mlwilkerson I think the best justification for it is so that this component can be installed via GitHub. This is a pretty typical use case:

```
yarn add https://github.com/FortAwesome/react-fontawesome.git
```

In that case the `index.js` and `index.es.js` need to be present.

**Comment by mlwilkerson** [comment]
OK, I'm convinced now. I don't think I've ever done a yarn add like that directly from GitHub. Still seems prone to update anomalies, but if it's a typical use case, users rule.

**Comment by robmadole** [comment]
Yeah, I would never recommend it but it is [documented](https://docs.npmjs.com/cli/install) and viable.

**Pull request merged**
