### PR TITLE
convert svg clip-path to clipPath for React

### PR DESCRIPTION
**Pull request by diligiant**
Fixes issue #10 

Signed-off-by: Frédéric Miserey <frederic@none.net>

### CODE REVIEW

**Comment by robmadole** [comment]
Looks like this broke a test @diligiant

**Comment by diligiant** [comment]
@robmadole just noticed. Will fix within the hour (i'm sure it work as we use it in prod ;)

**Comment by robmadole** [comment]
Yeah, I bet the test is brittle. Thanks for your help on all of this!

**Comment by robmadole** [comment]
@diligiant 0.0.9 released

**Pull request merged**
