### PR TITLE
Use forwardRef rather than custom `forwardedRef` prop

### LINKED ISSUE #199: Feature request: forwarding ref
### Describe the problem you'd like to see solved or task you'd like to see made easier

Passing a ref through a `FontAwesomeIcon` to access `SVGElement`

### Is this in relation to an existing part of react-fontawesome or something new?

Related the component `FontAwesomeIcon`

### Why would other react-fontawesome users care about this?

Integration with APIs that use DOMElement (like the [Tooltip of reactstrap](http://reactstrap.github.io/components/tooltips/))

### On a scale of 1 (sometime in the future) to 10 (absolutely right now), how soon would you recommend we make this feature?

7 - This year

### Feature request checklist

* [x] This is a single feature (i.e. not a re-write of all of Font Awesome)
* [x] The title starts with "Feature request: " and is followed by a clear feature name (Ex: `Feature request: moar cowbell`)
* [x] I have [searched for existing issues](https://github.com/FortAwesome/react-fontawesome/issues) and to the best of my knowledge this is not a duplicate

### PR DESCRIPTION
**Pull request by cpmsmith**
Closes #199.

As discussed in the issue, this is a breaking change.

This branch is based on #502, which can be merged separately.

### CODE REVIEW

**Comment by robmadole** [comment]
@cpmsmith ok this looks great. So now I'm thinking about documentation.

Since `forwardRef` was introduced in React 16.3.0 it seems like we can create a little table that describes what version of `react-fontawesome` you need based on the version of React. Something like this?

---

`react-fontawesome` now supports `forwardRef` for version `0.2.x` or above. This was a breaking change so if you are using React older than version 16.3.0 choose the `0.1.x` version of this component.

## Compatibility
| React version | react-fontawesome version |
| - | - |
| < 16.3.0 | 0.1.x |
| >= 16.3.0 | 0.2.x |

**Comment by cpmsmith** [comment]
@robmadole Yeah, sounds great to me!

**Comment by cpmsmith** [comment]
@robmadole Does this need anything more from me to be merged/released? I looked around for the website source, and didn't find anything—I assume it's private to you folks. Or did you mean we should put that table in this repo's readme?

**Comment by robmadole** [comment]
@cpmsmith no nothing more from you! I've just got a stack of stuff I'm workin through currently and I haven't made it down to this. I'll update the docs both in this repos README.md and on the fontawesome.com site. You are correct though the source code for our site is private so you won't find that anywhere. I hopefully can get to releasing this next week; or that's my goal.

**Comment by robmadole** [comment]
ok @cpmsmith I've got `0.2.0` released. I've also updated the README's on each branch to mention the difference between versions 0.1 and 0.2.

Thanks again for this work. Really appreciate it.

**Comment by BasudevBharatBhushan** [comment]
can we trigger click() event on fontawesome icons?

**Pull request merged**
