### PR TITLE
feature: add 0 to valid rotation values

### LINKED ISSUE #278: FontAwesome component should accept rotation 0.
If you have a let's say a button with an Icon and text in it, if you want to rotate the icon by 180 degrees every time it's pressed, it should be possible to just set the rotation prop to 0/180 respectively, however currently the only allowed numbers are 0,180 and 270. It would be a lot cleaner if the logic for rotation={0} would be inside the component.
image

### PR DESCRIPTION
**Pull request by baker-travis**
Fixes #278.

### CODE REVIEW

**Comment by robmadole** [comment]
@baker-travis should the tests be failing?

**Comment by baker-travis** [comment]
Whoops. It is now fixed @robmadole

**Comment by robmadole** [comment]
@baker-travis Font Awesome doesn't have a `fa-rotate-0` class does it?

**Comment by matbur** [comment]
What is status with this? If class `fa-rotate-0` doesn't exist in FA, maybe just ignore value `0` and do not return any class.

**Comment by robmadole** [comment]
This still needs to be fixed. We shouldn't apply `fa-rotate-0`. If the original author of this PR is not available I'll accept another PR from someone else.

**Pull request closed without merging**
