### PR TITLE
Allow React 15

### PR DESCRIPTION
**Pull request by craigcbrunner**
It would be useful for us if we could use this on React 15 projects, the code doesn't seem like it uses anything React 16 specific.

### CODE REVIEW

**Comment by calvinf** [comment]
You should be able to ignore the peer dependency and use React 15.  Since this library is only built and tested against 16, there's not really much reason for the maintainers to merge this change, but you should be able to use against React 15 "at your own risk".

**Comment by craigcbrunner** [comment]
The problem is when I try to build a component that works on either 15 or 16 the peer dep makes anything downstream using it also need to either have react 16 or modify their build settings. 

It works fine against 15 when I tested it

**Comment by robmadole** [comment]
We use Travis CI. If I could get a test matrix that included React 15 I'd merge that without hesitation. I'd love to support the older version but I won't unless the tests are automated.

**Comment by robmadole** [comment]
Enzyme is a [pretty good example](https://github.com/airbnb/enzyme/blob/master/.travis.yml) of a test matrix for this (although we don't need to match it exactly)

**Comment by calvinf** [comment]
For the Enzyme repo, they're making this work by using Lerna.js to create multiple packages in the same repository.  They have separate test adapter packages for each version of React they want to test against.

Enzyme's packages:
* https://github.com/airbnb/enzyme/tree/master/packages

Karma configuration where Enzyme wires up the different versions of their test adapters, etc:
* https://github.com/airbnb/enzyme/blob/master/karma.conf.js

Might be worth looking for a simpler approach for testing just React 15 and 16, but that seems to be how they do it.

**Pull request closed without merging**
