### PR TITLE
Update FontAwesomeIcon.js

### LINKED ISSUE #253: `width` in `FontAwesomeIcon` in `index.d.ts`
**Describe the bug**
To avoid flash-of-unstyled-svg, you need to default with element's width to zero. This would be a good bugfix.

In lieu of that, extending FontAwesomeIcon's Props to accept `width: number`, please.

### PR DESCRIPTION
**Pull request by haf**
Fixes #253 ; maybe; depending on your build pipeline.

### CODE REVIEW

**Comment by avin-kavish** [comment]
This would make the icon have 0 width, would it not?

**Comment by haf** [comment]
For a few milliseconds while the CSS is loading, yes. It therefore stops the flash-of-unstyled-content — SVGs taking up 100% of the viewport — that is the default with this lib right now. Besides that, this change explicitly lets you pass `width`; previously possible with a Typescript compiler error that had to be ignored.

**Comment by avin-kavish** [comment]
I've never seen a FUOC with react-fontawesome

**Comment by haf** [comment]
@avin-kavish Good for you. I have, which is one reason why I'm sending this PR. Yes, I'm saying that the react render loop runs before the css style sheet request, and there's no suspense or other 'check if css is loaded' in this lib.

The inline `width` attribute is **not** styles. It's a HTML **Presentational** Attribute. The full justification and inheritance chart can be read about here https://www.sarasoueidan.com/blog/svg-style-inheritance-and-fousvg/ but the TL;DR:

image

**Comment by haf** [comment]
> Why does it also say "depending on your build pipeline"?

Because depending on how (and I haven't checked) typescript definitions are generated, this fix may not cause the `.d.ts` files to be updated in `@types/react-fontawesome`, and in fact, it's unlikely since the fix is for a runtime/debug-level check, prop-types, and not towards the `@types` repo. While it's possible to extract TS types from prop-types, my guess is that that is not being done. So this fix would only fix the flash of unstyled content and not the typescript error that I linked to.

**Comment by avin-kavish** [comment]
Ok okay, looking at just your PR I couldn't understand you were referring to the width attribute. So I read the code here and the code in svg-core.

> Yes, I'm saying that the react render loop runs before the css style sheet request, and there's no suspense or other 'check if css is loaded' in this lib.

That's not the case, [Line 68 in the function component](https://github.com/FortAwesome/react-fontawesome/blob/2ea5ff19d51608465b527658580071a62e967eb2/src/components/FontAwesomeIcon.js#L68) is where svg-core is called in order to fetch the icon. If you follow that `icon()` call to [Line 2242 in the core library](https://github.com/FortAwesome/Font-Awesome/blob/master/js-packages/%40fortawesome/fontawesome-svg-core/index.es.js#L2242) you will see an `ensureCss` call on [Line 2265](https://github.com/FortAwesome/Font-Awesome/blob/538a5bc4cf7989821d052e3ff919e2bead07021c/js-packages/%40fortawesome/fontawesome-svg-core/index.es.js#L2265) which eventually calls `insertCss` on line 603. This library is setup in such a way to guarantee css insertion before the first icon is painted, as I would expect any decent developer to do so. And none of these calls are asynchrounous. If you are seeing a FUOC, this may indicate a bug somewhere along this chain of function calls most likely due to an interaction with your code or other dependencies.

react-fontawesome is merely a wrapper that calls the core library, it does not have any behaviour that deviates from it. Adding a width attribute to solve an issue originating somewhere else constitutes to a hack, which is fine for your project but this library needs to identify the root cause.

**Comment by haf** [comment]
I don't rely on the `autoAddCss` behaviour since that will fetch CSS outside of the webpack module, and your `ensureCss` function [only acts if that is enabled](https://github.com/FortAwesome/Font-Awesome/blob/538a5bc4cf7989821d052e3ff919e2bead07021c/js-packages/%40fortawesome/fontawesome-svg-core/index.es.js#L2126). I don't use it because it breaks the webpack ownership of CSS.

**Comment by avin-kavish** [comment]
> your ensureCss function

It's not my function,  it's open source

So you manually add css? Where and how do you do it?

**Comment by haf** [comment]
image

image

**Comment by haf** [comment]
Security docs I follow https://fontawesome.com/how-to-use/on-the-web/other-topics/security

**Comment by avin-kavish** [comment]
Okay, I imagine this is not a problem in production because you use a css extractor and link the styles in the head? Perhaps you linked the styles below the react scripts by mistake?

**Comment by haf** [comment]
@avin-kavish If I **link** the styles, they will cause a second HTTP request; the page will load unstyled at first and then style as the CSS files are read and parsed from the network. This is how all websites with non-inline or non-style-tag styles render styles. That's why FOUC is such a big thing. Like you can see from my screenshots, webpack takes care of resolving and downloading the style sheets; they are added as the module systems starts pulling in the dependencies. There's no mistake here.

The issue here is that SVG icons without a default with flash at 100% of the width, like the article I linked you describes. This is normal; which is why you provide **default** styles for the SVG logos and override those defaults with **CSS styles** afterwards.

Even if you're correct, it's a mute point, since this only provides an overridable default that doesn't affect other people than those who render the icons at 100%, which is not a "default" behaviour (especially given the Nx-css classes); and clearly possible to opt-in to by providing `svg { width: 100% }` in your style sheets.

**Comment by avin-kavish** [comment]
> If I link the styles, they will cause a second HTTP request; the page will load unstyled at first and then style as the CSS files are read and parsed from the network. This is how all websites with non-inline or non-style-tag styles render styles

No they don't. The HTML parser is paused when it hits a stylesheet. The stylesheet is loaded first before the parser resumes. Similar to when it encounters a non-deferred, non-async script. In production, extract the styles, link them in the head, then add the scripts just below the app root element.

More info:
https://www.filamentgroup.com/lab/async-css.html
https://bitsofco.de/async-vs-defer/

**Comment by robmadole** [comment]
Thanks @haf for taking the time to do this but this is not the solution we want to use to fix this.

**Comment by haf** [comment]
> No they don't. The HTML parser is paused when it hits a stylesheet. The stylesheet is loaded first before the parser resumes. Similar to when it encounters a non-deferred, non-async script. In production, extract the styles, link them in the head, then add the scripts just below the app root element.

This is not true for all use-cases of this project.

Let's say you're using the "styled jsx" syntax of nextjs, like I am; if you are then styles will be loaded together with the code that referenced it, and this means that you will have unstyled HTML loaded and rendered before the styles are applied as a subsequent response.

@robmadole You're making a mistake.

**Comment by robmadole** [comment]
It's not a mistake, it's a preference. I don't like this solution and we'll work to find another way. Thanks again for taking the time to put forth this PR.

**Pull request closed without merging**
