### PR TITLE
Add color prop to TypeScript definition

### PR DESCRIPTION
**Pull request by jdolle**
I am working on a TypeScript project and noticed the definition was missing `color`

### CODE REVIEW

**Comment by robmadole** [comment]
Hey @jdolle I don't think that `color` is a supported prop. Am I missing something?

**Comment by robmadole** [comment]
If it turns out I'm missing something just let me know and we can re-open this.

**Comment by jdolle** [comment]
@robmadole Sorry for not getting back earlier -- your [advanced example](https://github.com/FortAwesome/react-fontawesome#advanced) includes a color prop and I had tested locally with a color prop and it does change the color. I am not sure if that's part of your official API though or just a coincidence.

**Comment by robmadole** [comment]
Ah cool, thanks for finding that for me. I'll take a look at this 😕 because that's _not_ supposed to be there 😄

**Comment by robmadole** [comment]
@jdolle OK. This has been an education process for me. We accidentally supported this through the [SVG color attribute](https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/color). We pass along any additional attributes to the tag so this was just working. I thin @supercodepoet knew something that I didn't when he made that example. Like I said, I learned something today ;).

If you would be so kind to cherry-pick your commit on a fresh PR (we've force-pushed on `development`) I'll merge your PR. Also please make your PR against `development`. Thanks for being patient on this one.

**Pull request closed without merging**
